name: Deploy to Hugging Face Spaces

on:
  push:
    branches: [ main, develop ] 
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install fastapi uvicorn          

    - name: Test FastAPI app
      run: |
        python -c "from hf_app import app; print('FastAPI app loads successfully')"

  deploy-dev:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
    
    - name: Deploy to Development
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        echo "Deploying to DEVELOPMENT environment"
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        
        git clone https://huggingface.co/spaces/Eqqinox/futurisys-ml-api hf-space
        cd hf-space
        
        # Copier tous les fichiers nécessaires
        cp ../Dockerfile .
        cp ../hf_app.py .
        cp ../requirements.txt .
        cp ../README.md .
        
        # CRITICAL: Copier le dossier app/ complet
        cp -r ../app/ ./app/
        
        # Vérifier que app/ est bien copié
        echo "Contenu après copie:"
        ls -la
        echo "Contenu de app/:"
        ls -la app/ || echo "app/ directory not found after copy"
        
        git add .
        git commit -m "Deploy to DEV: ${{ github.sha }}" || exit 0
        git push https://Eqqinox:$HF_TOKEN@huggingface.co/spaces/Eqqinox/futurisys-ml-api main

  deploy-prod:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
    
    - name: Deploy to Production
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        echo "Deploying to PRODUCTION environment"
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        
        git clone https://huggingface.co/spaces/Eqqinox/futurisys-ml-api hf-space
        cd hf-space
        
        # Copier tous les fichiers nécessaires
        cp ../Dockerfile .
        cp ../hf_app.py .
        cp ../requirements.txt .
        cp ../README.md .
        
        # CRITICAL: Copier le dossier app/ complet
        cp -r ../app/ ./app/
        
        # Vérifier que app/ est bien copié
        echo "Contenu après copie:"
        ls -la
        echo "Contenu de app/:"
        ls -la app/ || echo "app/ directory not found after copy"
        
        git add .
        git commit -m "Deploy to PROD: ${{ github.sha }}" || exit 0
        git push https://Eqqinox:$HF_TOKEN@huggingface.co/spaces/Eqqinox/futurisys-ml-api main